"""Aumentar longitud del campo password

Revision ID: 037122a44757
Revises: b6b22d0eafbf
Create Date: 2024-10-10 21:19:12.853294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037122a44757'
down_revision = 'b6b22d0eafbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
